---
title: "ASSIGNMENT 5"
author: "Naveen Bagam"
date: '2022-01-30'
output:
  
  
  word_document: default
  html_document: default
  pdf_document: default
bibliography: bibliography.bib
---


## Set the working directory to the root of your DSC 520 directory
## setwd("/Users/nbaga/dsc520")
## Load the `data/r4ds/heights.csv
```{r }
heights_df <- read.csv("/Users/nbaga/dsc520/data/r4ds/heights.csv")

## Using `cor()` compute correclation coefficients for
## height vs. earn
cor(heights_df$height, heights_df$earn, method = "pearson")

### age vs. earn
cor(heights_df$age, heights_df$earn, method = "pearson")

### ed vs. earn
cor(heights_df$ed, heights_df$earn, method = "pearson")

## Spurious correlation
## The following is data on US spending on science, space, and technology in millions of today's dollars
## and Suicides by hanging strangulation and suffocation for the years 1999 to 2009
## Compute the correlation between these variables
tech_spending <- c(18079, 18594, 19753, 20734, 20831, 23029, 23597, 23584, 25525,27731, 29449)
suicides <- c(5427, 5688, 6198, 6462, 6635, 7336, 7248, 7491, 8161, 8578, 9000)
cor(tech_spending, suicides)

##Student Survey 

##The survey data is located in this StudentSurvey.csv file.

## I) Use R to calculate the covariance of the Survey variables and provide an explanation of why you would use this calculation and what the results indicate. 

student_survey <- read.csv("/Users/nbaga/dsc520/data/student-survey.csv")

 ## 1) Time Reading vs Happiness:- 
 
cov(as.numeric(student_survey$TimeReading),as.numeric(student_survey$Happiness), method = "pearson") 

  ## Expalantion of result:-
 
   ## The Timereading and Happiness negatively related, in other words , when the       Time of reading increases the Happiness is decreased .

##  2) Time TV vs  Happiness 
    cov(as.numeric(student_survey$TimeTV),as.numeric(student_survey$Happiness), method = "pearson") 
   
    ##Explanation :-
   
       ##The TimeTV and Happiness positively ralted, when TV time increased the   
       ## happiness is increased.
    
## 3) Time TV vs  TimeReading 
     cov(as.numeric(student_survey$TimeTV),as.numeric(student_survey$TimeReading), method = "pearson") 
      
    ##  EXplanation:- 
      
         ## TimeTV and TimeReading are negatively related, when ever people watch 
         ## more tv theor reading habbit is reduce. 
     
     
 ## II) Examine the Survey data variables. What measurement is being used for the variables? Explain what effect changing the measurement being used for the variables would have on the covariance calculation. Would this be a problem? Explain and provide a better alternative if needed.
     ## Explanation
      
        ## The measurement is used for the 3 variables Time TV in minutes and  TimeReading in hours and the Happiness is in the Percentage measure(%) , if we can keep all our variables in same measure the results would be correct.
     
## III) Choose the type of correlation test to perform, explain why you chose this test, and make a prediction if the test yields a positive or negative correlation?
     
     ##EXPLANATION
     
     ##relationship between two variables is to use the Pearson correlation coefficient,   which is a measure of the linear association between two variables. It always takes  on a value between -1 and 1 where:

## -1 indicates a perfectly negative linear correlation between two variables
## 0 indicates no linear correlation between two variables
## 1 indicates a perfectly positive linear correlation between two variables
     
##Perform a correlation analysis of:
   ## 1)All variables
          cor(student_survey)
   ## 2) A single correlation between two a pair of the variables
          cor(student_survey$TimeReading,student_survey$TimeTV)
   ## 3) Repeat your correlation test in step 2 but set the confidence interval at 99%   
          cor.test(student_survey$TimeReading,student_survey$TimeTV,conf.level=0.99)
   ## 4) Describe what the calculations in the correlation matrix suggest about the relationship between the variables. Be specific with your explanation.
          ## Explanation:- 
          ## Based on the calculation found that the 99 percent confidence  
          ## interval for the variables taken are : ##  -0.9801052 -0.4453124
          ## and the T-Value is t = -5.6457 and the p-value = 0.0003153 and the
          ## sample correlation is -0.8830677 whcih means the variables are
          ## negitively related
          ## variable increases the other one decreases and if one decreases the other one increase as well.
          
   ## 5) Calculate the correlation coefficient and the coefficient of determination, describe what you conclude about the results.
library(ggplot2)
        ggplot(student_survey) +  aes(x = TimeReading, y = TimeTV) +  geom_point(colour = "#0c4c8a") +
  theme_minimal()
          
   ## 6) Based on your analysis can you say that watching more TV caused students to read less? Explain.
        ##Explanation
        
        ##Yes, Based on the analysis we can conclude that watching TV more is causing less in reading.
        
   ## 7) Pick three variables and perform a partial correlation, documenting which variable you are “controlling”. Explain how this changes your interpretation and explanation of the results.
        library(ppcor)
        pcor(student_survey)
          
      ## From the above analysis , we can conclude that the if one variable is going up another variabvke is going dwon , when the TC time incerses the reading time is reduced.
     
     
     
     


